services:
  php:
    build:
      context: .
      dockerfile: DockerFile
    container_name: phpDeveloppementCube
    ports:
      - 8029:80
    volumes:
      - ./default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./:/var/www
    depends_on:
      - composer
      - db

  composer:
    image: composer:latest
    command: composer install --ignore-platform-reqs --no-interaction
    volumes:
      - .:/App
    working_dir: /App

  db:
    image: mysql:8.0
    container_name: mysqlDeveloppementCube
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
    ports:
      - 3312:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: webapplication
      PMA_PASSWORD: 653rag9T
      UPLOAD_LIMITE: 20M
    ports:
      - 8030:80

  phpunit:
    build:
      context: .
      dockerfile: DockerFile
    container_name: phpunit
    volumes:
      - .:/var/www
    working_dir: /var/www
    command: ./vendor/bin/phpunit --configuration phpunit.xml
    depends_on:
      - db

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui
    ports:
      - 8031:8080
    volumes:
      - ./public/swagger/openapi.json:/usr/share/nginx/html/api/openapi.json
    environment:
      SWAGGER_JSON: /usr/share/nginx/html/api/openapi.json