FROM php:8.2-apache

# Installer les utilitaires nécessaires, Git et activer mod_rewrite
RUN apt-get update && apt-get install -y --no-install-recommends \
    vim \
    git \
    && a2enmod rewrite \
    && service apache2 restart

# Définir le ServerName pour Apache
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf

# Installer les extensions PHP nécessaires
RUN docker-php-ext-install mysqli pdo pdo_mysql && docker-php-ext-enable mysqli pdo_mysql

# Copier les scripts d'initialisation
COPY init-preprod.sh /usr/local/bin/init-preprod.sh
COPY init-prod.sh /usr/local/bin/init-prod.sh

# Rendre les scripts exécutables
RUN chmod +x /usr/local/bin/init-preprod.sh /usr/local/bin/init-prod.sh

# Copier les fichiers de l'application
ADD . /var/www/

# Exposer le port 80
EXPOSE 80

