services:
  web:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/apache2/sites-enabled/000-default.conf
      - webdata-preprod:/var/www/html/preprod
    environment:
      - APACHE_LOG_DIR=/var/log/apache2
    depends_on:
      - db
    command: ["/bin/bash", "-c", "/usr/local/bin/init-preprod.sh"]

  db:
    image: mysql:8.0
    container_name: mysqlPreprodCube
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
    volumes:
      - dbdata-preprod:/var/lib/mysql

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadminPreprod
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: webapplication
      PMA_PASSWORD: 653rag9T
      UPLOAD_LIMITE: 20M
    ports:
      - 8030:80

volumes:
  dbdata-preprod:
  webdata-preprod:
