services :

  php:
    image: php:8.2-apache
    container_name: phpDeveloppementCube
    ports:
      - 8029:80
    volumes:
      - ./App:/var/www/app
      - ./Core:/var/www/core
      - ./logs:/var/www/logs
      - ./public:/var/www/html
      - ./style:/var/www/style
      - ./vendor:/var/www/vendor
      - ./:/var/www/src
    build:
      context: .
      dockerfile: DockerFile
    depends_on:
      - composer

  composer:
    image: composer:latest
    command: composer install --ignore-platform-reqs --no-interaction
    volumes:
      - .:/App
    working_dir: /App

  db:
    image: mysql:8.0
    container_name: mysqlDeveloppementCube
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: videgrenierenligne
      MYSQL_USER: webapplication
      MYSQL_PASSWORD: 653rag9T
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - 3312:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

  phpma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: webapplication
      PMA_PASSWORD: 653rag9T
      UPLOAD_LIMITE: 20M
    ports:
      - 8030:80